#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 {pull|create|start|enter|stop|delete|list} [arguments...]"
    exit 1
fi

command="python3 "

case "$1" in
    pull)
        command+="/usr/local/share/kunker/download_image.py"
        ;;
    create)
        command+="/usr/local/share/kunker/create_container.py"
        ;;
    start|enter|stop|delete|list)
        command+="/usr/local/share/kunker/operate_container.py $1"
        ;;
    *)
        echo "Unknown command \"$1\""
        exit 1
        ;;
esac

# 添加其他参数
shift
for arg in "$@"; do
    command+=" $arg"
done

# 执行命令
eval $command
